import { createContext, useContext, useEffect, useRef, useState, type MouseEvent, type ReactNode } from 'react'
import { basePath, categories, collections, imagery, official, sampleTitle, services, type Category, type Collection } from './data'
import './UndercoverDemo.css'

function Arrow({ diagonal = false }: { diagonal?: boolean }) {
  return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={diagonal ? 'M6 18 18 6M6 6h12v12' : 'M4 12h16m-6-6 6 6-6 6'} stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
}
function Sun({ className = '' }: { className?: string }) {
  return <svg className={className} viewBox="0 0 64 64" fill="none" aria-hidden="true"><path d="M32 6v52M6 32h52M13.6 13.6l36.8 36.8M13.6 50.4l36.8-36.8" stroke="currentColor" strokeWidth="5" strokeLinecap="round" /></svg>
}
function House() {
  return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m3 11 9-8 9 8M6 9v12h12V9M10 21v-6h4v6" stroke="currentColor" strokeWidth="1.3" strokeLinejoin="round" /></svg>
}
function Mark() {
  return <span className="ub-mark"><span className="ub-mark-window"><img src="/undercover-demo/undercover-logo-concept.png" width="2169" height="725" alt="undercover" decoding="async" /></span></span>
}
function Photo({ name, alt, className = '', eager = false }: { name: keyof typeof imagery; alt: string; className?: string; eager?: boolean }) {
  return <img className={className} src={imagery[name]} alt={alt} loading={eager ? 'eager' : 'lazy'} decoding="async" />
}

const NavigationContext = createContext<((event: MouseEvent<HTMLAnchorElement>, target: string) => void) | null>(null)
function Link({ to = '', children, className = '', label }: { to?: string; children: ReactNode; className?: string; label?: string }) {
  const navigate = useContext(NavigationContext)
  return <a href={`${basePath}${to ? `/${to}` : ''}`} onClick={e => navigate?.(e, to)} className={className} aria-label={label}>{children}</a>
}
function ButtonLink({ to, children, light = false }: { to: string; children: ReactNode; light?: boolean }) {
  return <Link to={to} className={`ub-button${light ? ' ub-button-light' : ''}`}>{children}<Arrow /></Link>
}
function Cards({ items }: { items: Collection[] }) {
  return <div className="ub-collection-grid">{items.map(c => <Link key={c.id} to={`collections/${c.id}`} className="ub-collection-card"><div className="ub-collection-photo"><Photo name={c.image} alt={`${c.category === 'spas' ? 'Spa' : c.category === 'saunas' ? 'Sauna' : 'Bedroom'} lifestyle from the Undercover website`} /><span className="ub-circle"><Arrow diagonal /></span></div><small>{c.eyebrow}</small><h3>{c.title}</h3><p>{c.description}</p></Link>)}</div>
}
function CategoryLinks() {
  return <div className="ub-category-grid">{(Object.keys(categories) as Category[]).map((key, index) => <Link to={key} className="ub-category-card" key={key}><Photo name={categories[key].image} alt={`${categories[key].title} inspiration from the official website`} /><div><small>0{index + 1} / YOUR EVERYDAY WELLNESS</small><h3>{key === 'spas' ? 'Soak.' : key === 'saunas' ? 'Restore.' : 'Rest.'}</h3><span>{categories[key].title}<span className="ub-circle"><Arrow diagonal /></span></span></div></Link>)}</div>
}
function Consultation({ title = 'Find your kind\nof feel-good.' }: { title?: string }) {
  return <section className="ub-consultation"><Sun className="ub-sun" /><div><p className="ub-eyebrow">A LITTLE GUIDANCE GOES A LONG WAY</p><h2>{title}</h2></div><div><p>From the first question to the finishing touch, discover the right fit with the local team.</p><ButtonLink to="contact" light>Let’s talk</ButtonLink><small>Design demo · Request preview only</small></div></section>
}

export default function UndercoverDemo({ initialPath = basePath }: { initialPath?: string }) {
  const [path, setPath] = useState(initialPath.replace(/\/+$/, '') || basePath)
  const [menuOpen, setMenuOpen] = useState(false)
  const [saved, setSaved] = useState<string[]>([])
  const [trayOpen, setTrayOpen] = useState(false)
  const main = useRef<HTMLElement>(null)
  const section = path.slice(basePath.length).replace(/^\//, '')

  useEffect(() => {
    const pop = () => { setPath(window.location.pathname.replace(/\/+$/, '')); setMenuOpen(false); setTrayOpen(false) }
    window.addEventListener('popstate', pop)
    return () => window.removeEventListener('popstate', pop)
  }, [])
  useEffect(() => { document.title = sampleTitle(path) }, [path])
  function navigate(event: MouseEvent<HTMLAnchorElement>, target: string) {
    if (event.button || event.ctrlKey || event.metaKey || event.shiftKey || event.altKey) return
    event.preventDefault()
    const destination = `${basePath}${target ? `/${target}` : ''}`
    window.history.pushState({}, '', destination)
    setPath(destination); setMenuOpen(false); setTrayOpen(false)
    window.scrollTo({ top: 0, behavior: 'instant' })
    requestAnimationFrame(() => main.current?.focus({ preventScroll: true }))
  }
  const collection = collections.find(c => section === `collections/${c.id}`)
  const category = section in categories ? section as Category : null
  let content: ReactNode
  if (!section) {
    content = <>
      <section className="ub-hero"><Photo name="hero" alt="Friends enjoying a Hot Spring spa on a garden patio, from the business’s website" eager /><div className="ub-hero-shade" /><div className="ub-hero-copy"><p className="ub-eyebrow"><span className="ub-dot" /> YOUR LOCAL ESCAPE, SINCE 1978</p><h1>Come home<br />to <em>feeling good.</em></h1><p>Warm soaks. Quiet moments. Better nights.<br />Make a little more room for you.</p><ButtonLink to="spas" light>Find your everyday escape</ButtonLink></div><div className="ub-hero-bottom"><span>SPAS · SAUNAS · MATTRESSES</span><Link to="visit">Rooted in Laramie. Made for your home.<Arrow diagonal /></Link></div><div className="ub-hero-index" aria-hidden="true">01 / THE ART OF UNWINDING</div></section>
      <div className="ub-trust-strip"><span><i><Sun /></i> Locally owned since 1978</span><span><i><House /></i> Downtown Laramie showroom</span><span><i><Arrow diagonal /></i> Wyoming & Northern Colorado</span></div>
      <section className="ub-section"><div className="ub-section-heading"><div><p className="ub-eyebrow">SMALL RITUALS. A BETTER EVERYDAY.</p><h2>Your space.<br /><em>Your kind of calm.</em></h2></div><p>A backyard retreat, a warm place to slow down, a bed you look forward to. Discover what feeling good at home looks like for you.</p></div><CategoryLinks /></section>
      <section className="ub-story"><div className="ub-story-photo"><Photo name="team" alt="The Undercover Bed & Spas team in their showroom" /><span>REAL PEOPLE. RIGHT HERE IN LARAMIE.</span></div><div className="ub-story-copy"><p className="ub-eyebrow">NEIGHBORS FIRST. WELLNESS ALWAYS.</p><h2>A local story.<br /><em>A lasting connection.</em></h2><p>Undercover Bed & Spas has been part of Wyoming life since 1978. Based in downtown Laramie, the locally owned business helps people across Wyoming and Northern Colorado create their own at-home retreat.</p><p>Explore thoughtfully chosen products, one-on-one guidance, and local installation and service support.</p><Link to="about" className="ub-text-link">Get to know Undercover<Arrow diagonal /></Link></div></section>
      <section className="ub-section ub-care"><div><p className="ub-eyebrow">HERE FOR THE LONG RUN</p><h2>More than a purchase.<br /><em>A little peace of mind.</em></h2><p>From monthly spa care to repairs and relocations, discover local support for the things you love.</p><ButtonLink to="services">Explore services & repairs</ButtonLink></div><div className="ub-service-list">{services.slice(0, 4).map(([title], i) => <Link key={title} to="services"><small>0{i + 1}</small><span>{title}</span><Arrow diagonal /></Link>)}</div></section>
      <Consultation />
    </>
  } else if (category) {
    const c = categories[category]
    content = <><section className="ub-page-hero"><div><p className="ub-eyebrow">{c.title.toUpperCase()}</p><h1>{c.phrase}</h1><p>{c.description}</p><a href="#collections" className="ub-text-link">Explore the collections<Arrow /></a></div><Photo name={c.image} alt={`${c.title} lifestyle from the official website`} eager /></section><section className="ub-section" id="collections"><div className="ub-section-heading"><div><p className="ub-eyebrow">FIND YOUR FIT</p><h2>Explore the collections.</h2></div><p>Browse the range, save your favorites, and get a feel for what belongs in your home. Pricing and availability are confirmed by the business.</p></div><Cards items={collections.filter(c => c.category === category)} /><p className="ub-image-note">Lifestyle imagery from the official website. Images represent inspiration; see the official catalog for individual product details.</p></section><Consultation /></>
  } else if (collection) {
    content = <><section className="ub-page-hero"><div><p className="ub-eyebrow">{collection.eyebrow.toUpperCase()}</p><h1>{collection.title}</h1><p>{collection.description}</p><ButtonLink to="contact">Preview a pricing request</ButtonLink><a href={`${official}${collection.source}`} className="ub-text-link" target="_blank" rel="noopener noreferrer">View the official collection<Arrow diagonal /></a></div><Photo name={collection.image} alt="Collection inspiration from the official Undercover website; not an individual model image" eager /></section><section className="ub-section"><div className="ub-section-heading"><div><p className="ub-eyebrow">A GOOD PLACE TO START</p><h2>{collection.category === 'spas' && !['spa-accessories', 'refurbished'].includes(collection.id) ? 'Meet the range.' : 'Explore your options.'}</h2></div><p>Save a few favorites in this demo. The showroom team can confirm specifications, finishes, stock, and pricing on the official site.</p></div><div className="ub-options">{collection.options.map((option, i) => {
      const favorite = `${collection.title} · ${option}`
      const active = saved.includes(favorite)
      return <article className="ub-option" key={option}><span className="ub-option-number">0{i + 1}</span><p className="ub-eyebrow">{collection.title}</p><h3>{option}</h3><p>Explore this {collection.category === 'spas' ? 'spa' : collection.category === 'saunas' ? 'sauna' : 'sleep'} option with the Undercover team.</p><button type="button" className="ub-save" aria-pressed={active} onClick={() => setSaved(active ? saved.filter(x => x !== favorite) : [...saved, favorite])}>{active ? '✓ Saved to your shortlist' : '+ Save to your shortlist'}</button></article>
    })}</div><p className="ub-image-note">Demo browsing only. Saving a favorite does not reserve stock or create an order. No prices or live availability are shown.</p></section><section className="ub-section ub-related"><p className="ub-eyebrow">KEEP EXPLORING</p><h2>A little more inspiration.</h2><Cards items={collections.filter(c => c.category === collection.category && c.id !== collection.id).slice(0, 3)} /></section><Consultation /></>
  } else if (section === 'services' || section === 'warranties') {
    content = <><section className="ub-page-hero"><div><p className="ub-eyebrow">LOCAL SUPPORT. LASTING COMFORT.</p><h1>{section === 'services' ? 'Good care.\nFor the long run.' : 'A little help\nwith the details.'}</h1><p>{section === 'services' ? 'Keep your home retreat in good hands, with maintenance, repairs, and support from the local service team.' : 'Warranty coverage depends on your product and purchase. Discover guidance from the Undercover team.'}</p><ButtonLink to="contact">Preview a service request</ButtonLink></div><Photo name="service" alt="An Undercover staff member beside a spa in the showroom" eager /></section><section className="ub-section"><p className="ub-eyebrow">SERVICES & REPAIRS</p><h2>Support that stays local.</h2><div className="ub-services-grid">{services.map(([title, description], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{description}</p><Link to="contact" className="ub-text-link">Preview an inquiry<Arrow /></Link></article>)}</div><div className="ub-resource-note"><p>Service needs, coverage, costs, and timing must be confirmed directly with the business.</p><a href={`${official}/services-and-repairs/`} target="_blank" rel="noopener noreferrer" className="ub-text-link">Official service information<Arrow diagonal /></a></div></section><Consultation /></>
  } else if (section === 'about') {
    content = <><section className="ub-about-intro ub-section"><p className="ub-eyebrow">DOWNTOWN LARAMIE · EST. 1978</p><h1>Rooted here.<br /><em>Here for you.</em></h1><p>A locally owned Wyoming business, helping neighbors find their everyday escape at home.</p><Photo name="team" alt="The real Undercover Bed & Spas team in their Laramie showroom" eager /></section><section className="ub-section ub-about-story"><div><p className="ub-eyebrow">THE UNDERCOVER STORY</p><h2>Comfort comes<br /><em>with connection.</em></h2></div><div><p>Since 1978, Undercover Bed & Spas has served Wyoming and Northern Colorado with spas, saunas, and mattresses. The downtown Laramie showroom brings those choices together in one place.</p><p>Founder and owner Mike Gapter and general manager Ariann McClurkin are part of the local team behind the business. Personal guidance, installation, maintenance, and repair support carry that relationship beyond the showroom.</p><ButtonLink to="visit">Find the showroom</ButtonLink><a href={`${official}/about-us/`} className="ub-text-link" target="_blank" rel="noopener noreferrer">Meet the team on the official site<Arrow diagonal /></a></div></section><section className="ub-section"><CategoryLinks /></section><Consultation /></>
  } else if (['visit', 'contact', 'brochure'].includes(section)) {
    content = <><section className="ub-contact-intro ub-section"><p className="ub-eyebrow">{section === 'brochure' ? 'YOUR NEXT CHAPTER STARTS HERE' : 'A LOCAL TEAM. A REAL CONVERSATION.'}</p><h1>{section === 'visit' ? <>Come by.<br /><em>Get comfortable.</em></> : section === 'brochure' ? <>A little inspiration.<br /><em>At your fingertips.</em></> : <>Let’s find<br /><em>your feel-good.</em></>}</h1><p>{section === 'visit' ? 'Find Undercover Bed & Spas at 400 South 2nd Street, in downtown Laramie.' : section === 'brochure' ? 'Explore a brochure request in this demo, or visit the official website for current product information.' : 'Explore a pricing or service inquiry. This preview keeps everything in your browser.'}</p></section><section className="ub-section ub-contact-grid"><div className="ub-visit-card"><p className="ub-eyebrow">THE LARAMIE SHOWROOM</p><h2>You’re always<br /><em>welcome here.</em></h2><address>400 South 2nd Street<br />Laramie, WY 82070</address><a href="https://www.google.com/maps/search/?api=1&query=Undercover+Bed+and+Spas+400+South+2nd+Street+Laramie+WY" target="_blank" rel="noopener noreferrer" className="ub-text-link">Get directions<Arrow diagonal /></a><div className="ub-hours"><div><span>Monday – Friday</span><span>10 am – 6 pm</span></div><div><span>Saturday</span><span>10 am – 4 pm</span></div><div><span>Sunday</span><span>Closed</span></div></div><p><a href="tel:+13077455289">(307) 745-5289</a><br /><a href="mailto:undercoverspa@gmail.com">undercoverspa@gmail.com</a></p><small>Contact links above connect to the real business.<br />Use the demo form to try the design without contacting anyone.</small></div><DemoForm key={section} brochure={section === 'brochure'} saved={saved} /></section></>
  } else if (section === 'guides') {
    content = <><section className="ub-section ub-contact-intro"><p className="ub-eyebrow">BLOG & GUIDES</p><h1>A little knowledge.<br /><em>A lot of possibility.</em></h1><p>Find inspiration and product reading on the official Undercover website.</p></section><section className="ub-section ub-guides"><Photo name="saunaInside" alt="Wood sauna interior with a round window from the official website" eager /><div><p className="ub-eyebrow">FROM THE UNDERCOVER BLOG</p><h2>Explore infrared<br /><em>sauna living.</em></h2><p>The official blog includes an article on five benefits of infrared saunas, published May 22, 2026.</p><a href={`${official}/blog-and-guides/`} target="_blank" rel="noopener noreferrer" className="ub-text-link">Read on the official website<Arrow diagonal /></a><Link to="brochure" className="ub-text-link">Preview a brochure request<Arrow /></Link></div></section><Consultation /></>
  } else {
    content = <section className="ub-section ub-not-found"><p className="ub-eyebrow">THIS PATH NEEDS A LITTLE RESET</p><h1>Let’s get you<br /><em>comfortable again.</em></h1><p>This page isn’t part of the demo. Browse the collections or return to the start.</p><ButtonLink to="">Back to the demo home</ButtonLink></section>
  }

  return <NavigationContext value={navigate}><div className="ub-demo" onClick={e => {
    const target = (e.target as Element).closest('a')
    if (target?.getAttribute('href')?.startsWith('#') && target.hash) document.querySelector(target.hash)?.scrollIntoView({ behavior: 'smooth' })
  }}>
    <a className="ub-skip" href="#ub-main">Skip to content</a>
    <div className="ub-demo-notice"><span>DESIGN PREVIEW BY WOLIN <span className="ub-notice-detail">· No orders or requests are sent.</span></span><a href={official} target="_blank" rel="noopener noreferrer">Official website<Arrow diagonal /></a></div>
    <header className="ub-header"><Link label="Undercover Bed and Spas demo home"><Mark /></Link><nav className={menuOpen ? 'ub-nav ub-nav-open' : 'ub-nav'} aria-label="Main navigation">{[['spas', 'Spas'], ['saunas', 'Saunas'], ['mattresses', 'Mattresses'], ['services', 'Services & repairs'], ['about', 'Our story']].map(([to, title]) => <Link key={to} to={to} className={section === to || collection?.category === to ? 'ub-active' : ''}>{title}</Link>)}<Link to="visit" className="ub-mobile-visit">Visit the showroom<Arrow /></Link></nav><div className="ub-header-actions"><button className="ub-shortlist-button" type="button" aria-label={`Shortlist${saved.length ? ` (${saved.length})` : ''}`} onClick={() => setTrayOpen(!trayOpen)} aria-expanded={trayOpen} aria-controls="ub-shortlist"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 3h12v18l-6-4-6 4V3Z" stroke="currentColor" strokeWidth="1.4" /></svg><span>Shortlist{saved.length ? ` (${saved.length})` : ''}</span></button><Link to="visit" className="ub-header-visit">Visit the showroom<Arrow diagonal /></Link><button type="button" className="ub-menu-button" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? '✕' : <><span /><span /></>}</button></div></header>
    {trayOpen && <aside className="ub-shortlist" id="ub-shortlist" aria-label="Your demo shortlist"><div><h2>Your shortlist</h2><button type="button" onClick={() => setTrayOpen(false)} aria-label="Close shortlist">✕</button></div><p>Demo only · Favorites stay in this page session. Nothing is reserved or sent.</p>{saved.length ? <><ul>{saved.map(item => <li key={item}><span>{item}</span><button type="button" aria-label={`Remove ${item}`} onClick={() => setSaved(saved.filter(x => x !== item))}>Remove</button></li>)}</ul><ButtonLink to="contact">Preview an inquiry</ButtonLink></> : <><p>No favorites yet. Explore a collection and save what catches your eye.</p><ButtonLink to="spas">Explore spas</ButtonLink></>}</aside>}
    {section && <div className="ub-breadcrumb"><Link>Home</Link><span>/</span>{collection && <><Link to={collection.category}>{categories[collection.category].title}</Link><span>/</span></>}<span>{collection?.title ?? (category ? categories[category].title : { services: 'Services & repairs', about: 'Our story', visit: 'Visit', contact: 'Contact', brochure: 'Brochures', guides: 'Blog & guides', warranties: 'Warranties' }[section] ?? 'Page not found')}</span></div>}
    <main id="ub-main" tabIndex={-1} ref={main}>{content}</main>
    <footer className="ub-footer"><div className="ub-footer-top"><div><Link><Mark /></Link><p>A little more comfort.<br />A little closer to home.</p><small>DOWNTOWN LARAMIE · SINCE 1978</small></div><div><h3>Find your feel-good</h3>{[['spas', 'Spas & cold plunge'], ['saunas', 'Saunas'], ['mattresses', 'Mattresses & sleep'], ['services', 'Services & repairs']].map(([to, text]) => <Link key={to} to={to}>{text}</Link>)}</div><div><h3>A little guidance</h3>{[['about', 'Our story'], ['guides', 'Blog & guides'], ['brochure', 'Brochures'], ['warranties', 'Warranty guidance'], ['contact', 'Contact & pricing']].map(([to, text]) => <Link key={to} to={to}>{text}</Link>)}</div><div><h3>Come say hello</h3><Link to="visit">400 South 2nd Street<br />Laramie, WY 82070</Link><a href="tel:+13077455289">(307) 745-5289</a><p>Mon–Fri 10 am–6 pm<br />Sat 10 am–4 pm · Sun closed</p><div className="ub-socials"><a href="https://www.instagram.com/undercoverbedandspas/" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href="https://www.facebook.com/UndercoverBedAndSpas" target="_blank" rel="noopener noreferrer">Facebook ↗</a></div></div></div><div className="ub-footer-bottom"><p>Unofficial frontend design demo by Wolin. Business content and photography sourced from <a href={official} target="_blank" rel="noopener noreferrer">the official Undercover website</a>. No orders, bookings, payments, or messages are processed.</p><span>MADE WITH CARE, IN LARAMIE <i><Sun /></i></span></div></footer>
  </div></NavigationContext>
}

function DemoForm({ brochure, saved }: { brochure: boolean; saved: string[] }) {
  const [previewed, setPreviewed] = useState(false)
  const status = useRef<HTMLDivElement>(null)
  return <div className="ub-form-card"><p className="ub-eyebrow">{brochure ? 'BROCHURE REQUEST PREVIEW' : 'CONTACT REQUEST PREVIEW'}</p><h2>{brochure ? 'Find your inspiration.' : 'Tell us what feels right.'}</h2><p className="ub-form-notice">Try the form. This demo does not submit, store, or send your details. Use sample information.</p><form onSubmit={e => { e.preventDefault(); setPreviewed(true); requestAnimationFrame(() => status.current?.focus()) }}><div className="ub-form-row"><label>First name <span>*</span><input name="firstName" autoComplete="off" placeholder="e.g. Alex" required /></label><label>Last name<input name="lastName" autoComplete="off" placeholder="e.g. Taylor" /></label></div><div className="ub-form-row"><label>Phone <span>*</span><input name="phone" type="tel" autoComplete="off" placeholder="e.g. (307) 555-0123" required /></label><label>Email<input name="email" type="email" autoComplete="off" placeholder="e.g. alex@example.com" /></label></div><div className="ub-form-row"><label>I’m interested in<select name="interest" defaultValue="Spas"><option>Spas</option><option>Saunas</option><option>Mattresses</option><option>Services & repairs</option><option>Something else</option></select></label><label>Preferred reply<select name="reply"><option>Phone</option><option>Email</option></select></label></div><label>{brochure ? 'What would you like to explore?' : 'How can we help?'} <span>*</span><textarea name="message" rows={4} placeholder="Tell us a little about your space and what you have in mind…" required defaultValue={saved.length ? `I’m interested in: ${saved.join(', ')}` : ''} /></label><label className="ub-checkbox"><input type="checkbox" required /><span>I understand this is a design demo and nothing will be sent to the business.</span></label><button className="ub-button" type="submit">Preview {brochure ? 'brochure' : 'my'} request<Arrow /></button><small>* Required for this demo preview only.</small></form>{previewed && <div className="ub-form-status" ref={status} tabIndex={-1} role="status"><strong>Preview complete. Nothing was sent.</strong><p>Your details remain in this form only. For a real inquiry, visit the official business website.</p><a href={`${official}/${brochure ? 'request-brochure' : 'contact'}/`} target="_blank" rel="noopener noreferrer">Open the official {brochure ? 'brochure request' : 'contact page'} ↗</a></div>}</div>
}
