import { useState, type FormEvent, type ReactNode } from 'react'
import './BusinessSite.css'

type Page = 'home' | 'social' | 'websites' | 'google' | 'ai'
type Plan = { name: string; price: string; cadence: string; description: string; features: string[]; featured?: boolean }

const services: { id: Exclude<Page, 'home'>; number: string; label: string; title: string; description: string; href: string }[] = [
  { id: 'social', number: '01', label: 'Show up in their feed', title: 'Social media', description: 'Content, publishing, and community support that make your business familiar before someone needs you.', href: '/social-media' },
  { id: 'websites', number: '02', label: 'Turn visits into customers', title: 'Websites + SEO', description: 'A sharp website and ongoing search work that help the right people find you and take the next step.', href: '/websites-seo' },
  { id: 'google', number: '03', label: 'Own the local moment', title: 'Google Business Profile', description: 'A complete, polished profile that helps nearby customers understand your business at a glance.', href: '/google-business-profile' },
  { id: 'ai', number: '04', label: 'Be ready for what is next', title: 'AI visibility', description: 'Keep your business information clear, current, and easy for AI search tools to discover and cite.', href: '/ai-search' },
]

const socialPlans: Plan[] = [
  { name: 'Social Presence', price: '$479', cadence: '/ month', description: 'A polished, consistent presence for businesses that need social media handled every month.', features: ['Two connected social platforms', 'Eight original content pieces per month', 'Custom captions and branded graphics', 'Photo, static, and carousel content', 'Monthly content calendar and scheduling', 'Profile information and links checked', 'One consolidated revision round', 'Monthly performance summary'] },
  { name: 'Social Momentum', price: '$879', cadence: '/ month', featured: true, description: 'More content, short-form video, and thoughtful audience engagement tied to real business goals.', features: ['Everything in Social Presence', 'Twelve original content pieces per month', 'Up to two short-form videos from supplied footage', 'Eight additional story frames', 'One monthly campaign or promotional theme', 'Comment and inbox monitoring three weekdays per week', 'Up to 40 routine responses per month', 'Monthly strategy call and lead tracking'] },
  { name: 'Social Partner', price: '$1,479', cadence: '/ month', description: 'Hands-on content, community management, and strategy for businesses ready to make social a priority.', features: ['Up to three social platforms', 'Sixteen original content pieces per month', 'Up to four short-form videos', 'Twelve additional story frames', 'One local 60-minute content session per month', 'Weekday comment and inbox monitoring', 'Up to 100 routine responses per month', 'Monthly campaign planning and strategy meeting', 'Quarterly competitor and content review'] },
]
const websitePlans: Plan[] = [
  { name: 'Website Care', price: '$99', cadence: '/ month', description: 'Reliable upkeep for a site that is already working for you.', features: ['Core software and content updates', 'Routine site health checks', 'Broken link and form checks', 'Basic performance monitoring', 'Monthly summary of completed work'] },
  { name: 'Search Growth', price: '$299', cadence: '/ month', featured: true, description: 'Steady maintenance plus practical SEO improvements.', features: ['Everything in Website Care', 'Search Console monitoring', 'Page titles, descriptions, and headings', 'Core service and location page improvements', 'Internal links and local keyword opportunities', 'Monthly SEO priorities and reporting'] },
  { name: 'Search Authority', price: '$599', cadence: '/ month', description: 'A broader ongoing program for businesses with more places to be found.', features: ['Everything in Search Growth', 'Technical SEO issue review', 'Site structure and structured data improvements', 'Content planning for services and FAQs', 'Conversion path and speed improvements', 'Quarterly strategy review'] },
]
const googlePlan: Plan = { name: 'Profile Refresh', price: '$279', cadence: 'one time', description: 'An audit and hands-on cleanup of the listing your customers see in Search and Maps.', features: ['Complete profile audit with prioritized findings', 'Categories, services, description, attributes, and links reviewed', 'Hours, service areas, address, phone, and contact details checked', 'Logo, cover image, and existing photos reviewed', 'Duplicate, suspended, or inaccurate listing issues flagged', 'Summary of changes and next steps'] }
const aiPlan: Plan = { name: 'AI Visibility', price: '$99', cadence: '/ month', description: 'A practical monthly review and improvement cycle to help AI tools understand and reference your business accurately.', features: ['AI visibility check across major AI search tools', 'Review of business mentions, accuracy, and citations', 'Recommendations for clearer website and profile information', 'Ongoing checks for changes in how your business appears', 'Monthly summary of findings and priorities'] }

function Arrow() { return <span aria-hidden="true">↗</span> }
function Visual({ kind }: { kind: Exclude<Page, 'home'> }) {
  if (kind === 'social') return <div className="business-visual visual-social" aria-label="Examples of social media content"><figure><img src="/projects/sparkz-hero.jpeg" alt="Lifestyle content example" /><figcaption>Make them stop scrolling.</figcaption></figure><figure><img src="/projects/shalom-01.webp" alt="Branded campaign example" /><figcaption>Give them a reason to care.</figcaption></figure><figure><img src="/portraits/caleb-salt-flats-car.jpg" alt="Behind the scenes content example" /><figcaption>Stay on their mind.</figcaption></figure></div>
  if (kind === 'websites') return <div className="business-visual visual-web" role="img" aria-label="Example of a responsive website and search result"><div className="visual-browser"><div className="visual-browser-top"><i /><i /><i /><span>yourbusiness.com</span></div><div className="visual-browser-body"><small>THE GOOD STUFF, CLOSE TO HOME</small><strong>Make a great<br />first impression.</strong><span>See what we do ↗</span></div></div><div className="visual-search-card"><span>SEARCH VISIBILITY</span><strong>Found when it matters.</strong><div><i /><i /><i /></div></div></div>
  if (kind === 'google') return <div className="business-visual visual-google" role="img" aria-label="Example of a Google Business Profile search result"><div className="visual-google-search"><b>G</b><span>coffee near me</span><i>⌕</i></div><div className="visual-google-card"><div className="visual-google-photo" /><div className="visual-google-copy"><small>BUSINESS PROFILE</small><strong>Willow &amp; Pine Coffee</strong><span>4.9 <b>★★★★★</b> · Coffee shop</span><p>Open now · Closes 6 PM</p><div><span>↗ Website</span><span>⌁ Directions</span><span>☎ Call</span></div></div></div></div>
  return <div className="business-visual visual-ai" role="img" aria-label="Illustration of a business being cited in AI search"><div className="visual-ai-prompt">✳ &nbsp; Where should I go for a local coffee shop?</div><div className="visual-ai-answer"><span>✦ AI SEARCH</span><p>Willow &amp; Pine Coffee is a neighborhood favorite, known for its welcoming atmosphere and fresh coffee.</p><div><i /> willowandpine.com <Arrow /></div></div><div className="visual-ai-star">✳</div></div>
}
function Header({ page }: { page: Page }) { return <header className="business-header"><a className="business-wordmark" href="/" aria-label="Wolin home">wolin.dev<span>.</span></a><nav className="business-nav" aria-label="Main navigation">{services.map(service => <a key={service.id} href={service.href} aria-current={page === service.id ? 'page' : undefined}>{service.title}</a>)}</nav><a className="business-header-link" href="#contact">Book a call <Arrow /></a></header> }
function Tags() { return <div className="business-tags" aria-label="What we do"><div>{['Social media', 'Google ranking', 'SEO', 'AI', 'Websites'].map((tag, index) => <span key={tag}>{index > 0 && <i aria-hidden="true" />}{tag}</span>)}</div></div> }
function Home() { return <><section className="business-home-hero" aria-labelledby="business-title"><div className="business-home-hero-inner"><span className="business-eyebrow"><i /> A creative growth studio for local businesses</span><h1 id="business-title">We will make your<br />business go <em>viral.</em></h1><div className="business-home-hero-foot"><p>Be the business people see, remember, and choose. We bring your social presence, website, local search, and AI visibility together.</p><a className="business-pill-button" href="#services">Explore what we do <Arrow /></a></div></div><div className="business-hero-decoration" aria-hidden="true">✳</div></section><Tags /><div className="business-home-intro" id="services"><span className="business-eyebrow">Four ways to grow</span><h2>Every place your next<br /><em>customer looks.</em></h2><p>Choose one place to start or connect the whole picture.</p></div>{services.map(service => <section className={`business-service-section service-${service.id}`} key={service.id} aria-labelledby={`service-${service.id}-title`}><div className="business-service-inner"><div className="business-service-copy"><span className="business-service-index">{service.number} / 04 <i /> {service.label}</span><h2 id={`service-${service.id}-title`}>{service.title}</h2><p>{service.description}</p><a className="business-text-link" href={service.href}>Explore {service.title.toLowerCase()} <Arrow /></a></div><Visual kind={service.id} /></div></section>)}</> }
function DetailHero({ page, eyebrow, title, emphasis, description }: { page: Exclude<Page, 'home'>; eyebrow: string; title: string; emphasis: string; description: string }) { return <section className={`business-detail-hero detail-${page}`} aria-labelledby="business-title"><div className="business-detail-hero-inner"><div className="business-detail-copy"><span className="business-eyebrow"><i /> {eyebrow}</span><h1 id="business-title">{title}<br /><em>{emphasis}</em></h1><p>{description}</p><a className="business-pill-button" href="#pricing">Explore pricing <Arrow /></a></div><Visual kind={page} /></div></section> }
function Story({ eyebrow, title, emphasis, description }: { eyebrow: string; title: string; emphasis: string; description: string }) { return <section className="business-detail-story"><span className="business-eyebrow">{eyebrow}</span><h2>{title}<br /><em>{emphasis}</em></h2><p>{description}</p></section> }
function PricingCard({ plan, index }: { plan: Plan; index: number }) { return <article className={`business-pricing-card${plan.featured ? ' is-featured' : ''}`}><div className="business-pricing-card-top"><span>{String(index + 1).padStart(2, '0')} / PLAN</span>{plan.featured && <span className="business-popular">Most popular</span>}</div><h3>{plan.name}</h3><div className="business-pricing-price"><strong>{plan.price}</strong><span>{plan.cadence}</span></div><p className="business-pricing-description">{plan.description}</p><ul className="business-feature-list">{plan.features.map(feature => <li key={feature}><span aria-hidden="true">↗</span>{feature}</li>)}</ul><a href="#contact">Let’s talk about it <Arrow /></a></article> }
function Pricing({ eyebrow, title, description, plans, note }: { eyebrow: string; title: string; description: string; plans: Plan[]; note?: ReactNode }) { return <section className="business-pricing" id="pricing" aria-labelledby="pricing-title"><div className="business-pricing-heading"><span className="business-eyebrow">{eyebrow}</span><h2 id="pricing-title">{title}</h2><p>{description}</p></div><div className="business-pricing-grid">{plans.map((plan, index) => <PricingCard key={plan.name} plan={plan} index={index} />)}</div>{note && <p className="business-pricing-note">{note}</p>}</section> }
function Social() { return <><DetailHero page="social" eyebrow="Social media management" title="Show up. Stand out." emphasis="Stay connected." description="We plan, create, publish, and help manage your social presence so your business stays part of the conversation." /><Story eyebrow="More than posting" title="Content with a reason" emphasis="to exist." description="Each plan pairs a consistent publishing rhythm with a clear brand voice. Higher tiers add video, engagement, and hands-on strategy." /><Pricing eyebrow="Social media plans" title="Choose your pace." description="Monthly management packages for different stages of growth." plans={socialPlans} note="Social plans begin with a three-month engagement. Advertising spend is separate, and every account remains yours." /></> }
function Websites() { return <><DetailHero page="websites" eyebrow="Websites + SEO" title="Built to impress." emphasis="Built to be found." description="Get a website that makes a strong first impression, then keep it healthy and discoverable as your business grows." /><Story eyebrow="A strong foundation" title="One website build." emphasis="Ongoing momentum." description="The website is a one-time project tailored to your business. After launch, choose the level of maintenance and SEO support that fits your goals." /><section className="business-build-banner" aria-label="One-time website build"><div><span>01 / THE FOUNDATION</span><h2>Custom website build</h2><p>Strategy, design, development, mobile polish, and a clear path for customers to contact you.</p></div><div><strong>$1,999</strong><span>one-time starting price</span><a href="#contact">Discuss your website <Arrow /></a></div></section><Pricing eyebrow="Ongoing website + SEO" title="Keep growing after launch." description="Monthly care and search packages, with final scope tailored to your site." plans={websitePlans} note="Website build pricing starts at $1,999. Final pricing depends on the site’s size and requested features." /></> }
function Google() { return <><DetailHero page="google" eyebrow="Google Business Profile" title="Be the business" emphasis="they find nearby." description="Give customers a complete, trustworthy profile when they search Google or Maps for what you do." /><Story eyebrow="Local search essentials" title="Make every first look" emphasis="count." description="We review and improve the core details of your profile so people can understand your services, hours, location, and next step." /><Pricing eyebrow="One-time profile setup" title="A clear starting point." description="A focused, one-time optimization for your Google Business Profile." plans={[googlePlan]} /></> }
function Ai() { return <><DetailHero page="ai" eyebrow="AI search visibility" title="Be part of" emphasis="the answer." description="More customers are asking AI tools what to buy and where to go. We help your business stay clear, accurate, and discoverable in those conversations." /><Story eyebrow="The next search surface" title="Make it easier for AI" emphasis="to understand you." description="We review how your business appears in AI search, look for gaps or inaccuracies, and keep the information these tools rely on up to date." /><Pricing eyebrow="AI visibility plan" title="Stay in the conversation." description="Simple monthly support for a fast-changing way people discover businesses." plans={[aiPlan]} note="AI search results change often. Visibility and placement cannot be guaranteed." /></> }
function ContactForm() { const [status, setStatus] = useState<'idle' | 'submitting' | 'success' | 'error'>('idle'); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; setStatus('submitting'); try { const response = await fetch('/api/visibility-report', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(form).entries())) }); if (!response.ok) throw new Error('Contact failed'); form.reset(); setStatus('success') } catch { setStatus('error') } }; return <form className="business-contact-form" onSubmit={submit}><label className="business-honeypot" aria-hidden="true">Company<input name="company" type="text" tabIndex={-1} autoComplete="off" /></label><label>Name<input name="name" type="text" autoComplete="name" placeholder="Your name" required /></label><label>Email<input name="email" type="email" autoComplete="email" placeholder="you@business.com" required /></label><label>Phone<input name="phone" type="tel" autoComplete="tel" placeholder="(555) 555-5555" /></label><label>Business website<input name="website" type="url" autoComplete="url" placeholder="https://yourbusiness.com" /></label><label className="is-wide">What can we help with?<select name="service" defaultValue=""><option value="" disabled>Select a service</option><option>Social media</option><option>Websites + SEO</option><option>Google Business Profile</option><option>AI visibility</option><option>A few things</option></select></label><label className="is-wide">Tell us a little more<textarea name="message" rows={3} placeholder="What are you working toward?" /></label><button type="submit" disabled={status === 'submitting'}>{status === 'submitting' ? 'Sending…' : 'Get in touch'} <Arrow /></button><p className={`business-form-status is-${status}`} role={status === 'error' ? 'alert' : 'status'} aria-live="polite">{status === 'success' ? 'Thanks! Your message was sent. I’ll be in touch soon.' : status === 'error' ? 'That did not go through. Please email me directly at caleb.wolin@gmail.com.' : ''}</p></form> }
function BusinessSite({ page = 'home' }: { page?: Page }) { return <div className="business-site"><a className="business-skip" href="#main">Skip to content</a><Header page={page} /><main id="main">{page === 'home' ? <Home /> : page === 'social' ? <Social /> : page === 'websites' ? <Websites /> : page === 'google' ? <Google /> : <Ai />}</main><footer className="business-footer" id="contact"><div className="business-footer-inner"><div className="business-footer-copy"><span className="business-eyebrow"><i /> Ready when you are</span><h2>Let’s make your<br />business <em>impossible<br />to miss.</em></h2><p>Tell me what you’re building. We’ll find a good time to talk through where your business can go next.</p><div className="business-footer-direct"><span>Prefer to reach out directly?</span><a href="mailto:caleb.wolin@gmail.com">caleb.wolin@gmail.com <Arrow /></a><a href="tel:+12088108089">+1 (208) 810-8089 <Arrow /></a></div></div><div className="business-footer-form"><div className="business-footer-form-heading"><span>START A CONVERSATION</span><h3>Book a call.</h3></div><ContactForm /></div></div><div className="business-footer-bottom"><span>Wolin © 2026</span><a href="#main">Back to top ↑</a></div></footer></div> }
export default BusinessSite
